### ISSUE TITLE
Expose memes as image endpoint

### ISSUE THREAD

**Issue by tobloef** [madswolf/MemeApi#5]
It would be cool to expose a .png endpoint that gives you a random meme. And including the ids in the response header would also be neat!

**Comment by madswolf** [comment]
This is a great suggestion!
I think a barebones endpoint that generates a random meme and returns the rendered image in the response is a great way to make these memes easier to use. 

In the spirit of this, it might make sense to let you predetermine some of the components of the meme with optional ID's on the incoming requests since the rendering logic will be the same.
